USE rulebased;
CREATE TABLE IF NOT EXISTS names 		(nid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS substances		(sid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,formula TEXT);
CREATE TABLE IF NOT EXISTS parameters		(pid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,description TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS parameters_substances(pid INT NOT NULL, sid INT NOT NULL, abbrevation CHAR NOT NULL, specification TEXT,selector VARCHAR(10),refered_substance_sid INT);
CREATE TABLE IF NOT EXISTS names_substances	(nid INT NOT NULL,sid INT NOT NULL, PRIMARY KEY(nid,sid));


SHOW TABLES;
